inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6
Metrics/BlockLength:
  ExcludedMethods:
    - describe
Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*'
Metrics/AbcSize:
  Exclude:
    - 'spec/**/*'
