matrix:
  include:
    - language: node_js
      cache:
        npm: true
        yarn: true
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      script:
        - yarn lint
        - yarn test:ci
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
    - language: ruby
      sudo: false
      cache: bundler
      rvm:
        - 2.6.0
      before_install: gem install bundler -v 1.17.2
